version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/variants/esp32"
    schedule:
      interval: "daily"
      time: "06:00" # UTC
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00" # UTC
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
